# Generated by Django 5.1.7 on 2025-03-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_code', models.CharField(max_length=50, unique=True)),
                ('thumb_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh mục sản phẩm',
                'verbose_name_plural': 'Quản lý danh mục sản phẩm',
                'db_table': 'product_categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_record', models.IntegerField()),
                ('family_id', models.CharField(max_length=50, unique=True)),
                ('marketing_name', models.CharField(max_length=255)),
                ('eng_name', models.CharField(max_length=255)),
                ('product_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Quản lý sản phẩm',
                'db_table': 'product_families',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=50, unique=True)),
                ('model_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('thumb_url', models.URLField(blank=True, null=True)),
                ('thumb_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('large_url', models.URLField(blank=True, null=True)),
                ('pdp_url', models.URLField(blank=True, null=True)),
                ('ratings', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('stock_status', models.CharField(default='inStock', max_length=50)),
                ('price', models.IntegerField()),
                ('promotion_price', models.IntegerField(blank=True, null=True)),
                ('formated_price_save', models.CharField(blank=True, max_length=255, null=True)),
                ('marketing_message', models.TextField(blank=True, null=True)),
                ('sales_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.productfamily')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Quản lý biến thể sản phẩm',
                'db_table': 'product_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Quản lý hình ảnh sản phẩm',
                'db_table': 'product_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChipOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_type', models.CharField(max_length=50)),
                ('chip_code', models.CharField(max_length=50)),
                ('chip_name', models.CharField(max_length=255)),
                ('chip_local_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_options', to='products.productmodel')),
            ],
            options={
                'verbose_name': 'Chip option',
                'verbose_name_plural': 'Quản lý chip option',
                'db_table': 'chip_options',
                'ordering': ['-created_at'],
            },
        ),
    ]
