# Generated by Django 5.1.7 on 2025-03-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chipoption',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chip option', 'verbose_name_plural': 'Chip option'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hình ảnh biến thể', 'verbose_name_plural': 'Hình ảnh biến thể'},
        ),
        migrations.AddField(
            model_name='productfamily',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
            preserve_default=False,
        ),
    ]
