# Generated by Django 5.1.7 on 2025-03-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_chipoption_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='formated_price_save',
            new_name='formatted_price_save',
        ),
    ]
