# Generated by Django 5.1.7 on 2025-03-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productmodel_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='marketing_message',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sales_text',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
