# Generated by Django 5.1.7 on 2025-03-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_marketing_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='marketing_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sales_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
