# Generated by Django 5.1.7 on 2025-03-15 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productmodel_marketing_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Loại chip',
                'verbose_name_plural': 'Quản lý loại chip',
                'db_table': 'chip_types',
            },
        ),
        migrations.AlterModelOptions(
            name='chipoption',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chip option', 'verbose_name_plural': 'Quản lý chip option'},
        ),
        migrations.AlterField(
            model_name='chipoption',
            name='chip_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.chiptype'),
        ),
    ]
