# Generated by Django 5.1.7 on 2025-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_chiptype_alter_chipoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipoption',
            name='chip_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelOptions(
            name='chipoption',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chip option', 'verbose_name_plural': 'Chip option'},
        ),
        migrations.DeleteModel(
            name='ChipType',
        ),
    ]
