# Generated by Django 5.1.7 on 2025-03-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_chipoption_chip_type_alter_chipoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfamily',
            name='marketing_name',
            field=models.CharField(max_length=255, verbose_name='Tên thương mại'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='display_name',
            field=models.CharField(max_length=255, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='model_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã SKU'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='promotion_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stock_status',
            field=models.CharField(default='inStock', max_length=50, verbose_name='Trạng thái'),
        ),
    ]
